# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-28 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='pda',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='url',
            name='upa',
            field=models.FloatField(default=0),
        ),
    ]
